import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "学习栏目",
      icon: "graduation-cap",
      children: [
        { text: "后端开发", icon: "server", link: "/backend/" },
        { text: "算法与数据结构", icon: "diagram-project", link: "/algorithm/" },
        { text: "计算机基础", icon: "desktop", link: "/computer-fundamentals/" },
        { text: "开发工具", icon: "screwdriver-wrench", link: "/tools/" },
        { text: "AI 应用开发", icon: "robot", link: "/ai-application-development/" },
        { text: "前端开发", icon: "laptop-code", link: "/frontend/" },
        { text: "学习路线", icon: "map", link: "/learning-paths/" },
        { text: "资源导航", icon: "compass", link: "/resources/" },
        { text: "网站维护指南", icon: "book-open", link: "/site-guide/" },
      ],
    },
    { text: "关于作者", icon: "user", link: "/portfolio" },
  ],

  "/backend/": [
    {
      text: "后端开发",
      icon: "server",
      link: "/backend/",
    },
    {
      text: "GO",
      icon: "terminal",
      link: "/backend/go/",
      collapsible: true,
      collapsed: false,
      children: [
        {
          text: "Golang 基础知识",
          icon: "book-open",
          collapsible: true,
          collapsed: false,
          prefix: "go/basic/",
          children: "structure",
        },
        {
          text: "Golang 进阶知识",
          icon: "rocket",
          collapsible: true,
          collapsed: false,
          prefix: "go/advanced/",
          children: "structure",
        },
      ],
    },
    {
      text: "Java",
      icon: "mug-hot",
      collapsible: true,
      collapsed: false,
      prefix: "java/",
      children: "structure",
    },
    {
      text: "数据库",
      icon: "database",
      collapsible: true,
      collapsed: false,
      prefix: "database/",
      children: "structure",
    },
    {
      text: "消息队列",
      icon: "tower-broadcast",
      collapsible: true,
      collapsed: false,
      prefix: "message-queue/",
      children: "structure",
    },
    {
      text: "微服务与分布式",
      icon: "share-nodes",
      collapsible: true,
      collapsed: false,
      prefix: "microservices/",
      children: "structure",
    },
  ],

  "/algorithm/": "structure",
  "/computer-fundamentals/": "structure",
  "/tools/": "structure",
  "/frontend/": "structure",
  "/ai-application-development/": "structure",
  "/learning-paths/": "structure",
  "/resources/": [
    { text: "资源导航", icon: "compass", link: "/resources/" },
    { text: "常用搜索", icon: "magnifying-glass", link: "/resources/#常用搜索" },
    { text: "编程学习", icon: "graduation-cap", link: "/resources/#编程学习" },
    { text: "代码托管", icon: "code-branch", link: "/resources/#代码托管" },
    { text: "官方文档", icon: "book-open", link: "/resources/#官方文档" },
    { text: "AI 工具", icon: "robot", link: "/resources/#ai-工具" },
    { text: "模型 API 与订阅", icon: "brain", link: "/resources/#模型-api-与订阅" },
    { text: "云服务", icon: "cloud", link: "/resources/#云服务" },
    { text: "建站与个人项目", icon: "blog", link: "/resources/#建站与个人项目" },
    { text: "使用建议", icon: "lightbulb", link: "/resources/#使用建议" },
  ],
  "/site-guide/": "structure",
});
